### ISSUE TITLE
Makerstrap: The Next Generation

### ISSUE THREAD

**Issue by gvn** [mozilla/mofo-cms-experiment#4]
Let's explore what a new version of [Makerstrap](https://github.com/mozilla/makerstrap) might encompass.

Subject to change, but my initial strategic thoughts :
- Do a fresh, ground-up theme for Bootstrap 4.
- Use Sass (Also, related: suggest codifying our front-end practices similar to our JS style guide).
- Base the theme off our new [MLN style guide](https://redpen.io/ywb006488f91162838).
- Start with typography and color palettes only.
- Stop using Bower. Just _npm-all-the-things_.

There's some risk in using Bootstrap 4 as it's [in alpha](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/), but there's also risk in using a soon-to-be-outdated version. My assumption, that needs validation, is that the implementation is mostly staying the same (eg: class names won't change), but the underlying architecture is being revamped.

**TODO**
- [x] Research Bootstrap 4 (@gvn, @vazquez)
- [x] Spin up a repo for ~~Makerstrap 2~~ Foxlight (@gvn)
- [ ] Determine if the MLN style guide is ready for implementation, and if it's the right style guide to use (@vazquez)

**Comment by gvn** [comment]
CC: @simonwex @mmmavis

**Comment by gvn** [comment]
Also, @thomaspark, I'd love to hear your thoughts since I know you're very involved w. Bootstrap!

**Comment by vazquez** [comment]
##### Bootstrap 4 Findings (Front-end focused)

Some of these findings are obvious but they deserve the shout-out:
- Installable with NPM
- Written in SCSS
- Supported by all desktop browsers
- Supported by all mobile browsers expect for Opera Mini
- Flexbox can be enabled through a boolean variable
- Media query breakpoints are now written in `em`values (as opposed to px in Bootstrap 3)
- Bootstrap 4 grids are as awesome as always, and now contain helpful Sass Mixins
- Responsive classes are available for showing and hiding content by device by media query.

**Comment by thomaspark** [comment]
Hi all, here's a nice rundown of [changes in v4](http://v4-alpha.getbootstrap.com/migration/). @gvn, I think you're right in that the architecture is reworked, but the markup "API" is mostly unchanged.

One big change though is dropping IE8 (and iOS6). If you want to support them, you should stick with v3.

If not, v4 is the way to go since it's Sass-first and will be better maintained and optimized going forward.

**Comment by gvn** [comment]
Awesome, thanks @thomaspark ! That's very helpful.

I'm moving forward with Bootstrap 4 for our new theme, [Foxlight](https://github.com/gvn/foxlight). :+1: 

So far so good!

**Comment by simonwex** [comment]
:+1: !

**Comment by mmmavis** [comment]
:exclamation: This ticket is now locked. Please continue the discussion on https://github.com/mozilla/wp-calypso instead. For more info see [README](https://github.com/mozilla/mofo-cms-experiment).
